services:
  - type: web
    name: kwang-web-frontend
    env: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        value: https://kwangwebback-new.railway.internal
      - key: NUXT_PUBLIC_API_BASE_URL
        value: https://kwangwebback-new.railway.internal
